version: "3.7"
services:
        ocp-haproxy:
                build: .
                image: ocp-haproxy:2.1.4
                restart: always
                container_name: ocp-haproxy
                hostname: ocp-haproxy
                network_mode: bridge
                ports:
                        - 80:80
                        - 443:443
                        - 6443:6443
                        - 22623:22623
